In [70]:
from bs4 import BeautifulSoup
import urllib

from selenium import webdriver


import os
import pandas as pd
import numpy as np
import pickle
import re
import time

import string

In [94]:
chromedriver = './chromedriver/chromedriver'
os.environ["webdriver.chrome.driver"] = chromedriver
driver = webdriver.Chrome(executable_path = chromedriver)

In [89]:
urls = []

for pageno in range(0,100):
    print(pageno)
    url = 'https://uk.reuters.com/news/archive/oilRpt?view=page&page='+str(pageno)+'&pageSize=10'
    driver.get(url)
    time.sleep(3 + 8*np.random.uniform())

    soup = BeautifulSoup(driver.page_source, 'lxml')
    for div in soup.find_all('div', attrs={'class': 'story-content'}):
        url = 'https://uk.reuters.com{}'.format((div.findAll('a')[0].attrs['href']))
        urls.append(url)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99

In [90]:
driver.close()

In [114]:
len(urls)

1000

In [117]:
news_text = []
title = []

for i,url in enumerate(urls[0:500]):
    if i == len(urls):
        print('Last')
    else:
        print(i)
    driver.get(url)
    time.sleep(2+5*np.random.uniform())
    
    try:
        soup = BeautifulSoup(driver.page_source,'lxml')
        for div in (soup.find_all('h1', attrs={'class': 'headline_2zdFM'})):
            news = div.text.replace('\n', '')
            title.append(news)
    except AttributeError:
        title.append('NA')   
    
    try:
        soup = BeautifulSoup(driver.page_source,'lxml')
        for div in (soup.find_all('div', attrs={'class': 'body_1gnLA'})):
            news = div.text.replace('\n', '')
            news_text.append(news)
    except AttributeError:
        news_text.append('NA')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499

In [118]:
data_dict_1 = {'title': title, 'news_text': news_text}
df_1 = pd.DataFrame(data_dict_1)
df_1.head()

,news_text,title
0,SINGAPORE (Reuters) - Oil prices fell on Monda...,"Oil prices drop as Saudi, Russian output rises..."
1,"SINGAPORE, July 2 (Reuters) - Crude oil trader...",MOVES-ExxonMobil hires crude trader in Singapo...
2,(Repeats late Friday item without changes) By ...,RPT-GRAPHIC-Trillion dollar wipeout: world sto...
3,SYDNEY (Reuters) - A renewed slide in Chinese ...,"China drags on Asia shares, politics on euro a..."
4,(Corrects location of plant in fourth paragrap...,CORRECTED-Norway's REC Silicon lays off nearly...

In [119]:
len(df_1)

500

In [120]:
df_1 = pickle.dump(df_1, open('news_oil.pkl', 'wb'))

In [123]:
df_1 = pickle.load(open('news_oil.pkl', 'rb'))

In [135]:
df_1['news_text'][29]

'SEOUL (Reuters) - State-run utility Korea Electric Power Corp (015760.KS) (KEPCO) had been shortlisted to bid for a nuclear project in Saudi Arabia along with the United States, France, China and Russia, South Korea’s energy ministry said on Sunday.   “We were informed by our Saudi counterpart, King Abdullah City for Atomic and Renewable Energy, that KEPCO was shortlisted for a nuclear project in Saudi Arabia,” the ministry said in a statement.  The statement said the winner of the tender was expected to be chosen in 2019.   Saudi Arabia, the world’s top oil producer, plans to build two nuclear plants to diversify its energy supply and has been in talks with companies from South Korea, the United States, Russia and China for the tender.  In May, Saudi Arabian Energy Minister Khalid al-Falih met South Korean Energy Minister Paik Un-gyu in Seoul. Falih told reporters on the sidelines of an industry event that he was “optimistic” about South Korea being on the tender shortlist.    Korea Electric Power Corp32450.0015760.KSKorea Stock Exchange+450.00(+1.41%)015760.KSSouth Korea, the world’s fifth-biggest nuclear power user, is seeking to export its nuclear reactors abroad.  In 2009, a South Korean consortium led by KEPCO won an $18.6 billion (14.08 billion pounds) deal to construct four nuclear plants in the United Arab Emirates, the country’s ever nuclear export success.  KEPCO was also selected as a preferred bidder in December last year for Toshiba’s NuGen nuclear project in Britain and the Korean company planned to talk with Toshiba to buy a stake in the project. Reporting By Jane Chung and Cynthia Kim. Editing by Jane MerrimanOur Standards:The Thomson Reuters Trust Principles.'